export const NEXT_PUBLIC_GTM_ID = process.env.NEXT_PUBLIC_GTM_ID
export const NEXT_PUBLIC_GITHUB_CLIENT_ID =
  process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID
export const NEXT_PUBLIC_GITHUB_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_GITHUB_CLIENT_SECRET
export const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY
export const NEXT_PUBLIC_STRIPE_PUBLISH_KEY =
  process.env.NEXT_PUBLIC_STRIPE_PUBLISH_KEY
